# Description : Constant for the game
import pygameMenu

# MENU CONFIGURATION
MENU_BG_COLOR = (186, 190, 196)
# MENU_COLOR = (108, 115, 126)
MENU_COLOR_TITLE = (108, 115, 126)

# FONT FOR THE GAME
FONT = pygameMenu.font.FONT_HELVETICA

# MISC. CONFIGURATION FOR THE GAME
WIDTH = 832
HEIGHT = 832
WINDOW_TITLE = "Blindfolded"
FRAMERATE = 30

# PORT FOR SOCKET CONNECTION
PORT = 37666
# TIMEOUT FOR SOCKET CONNECTION
SOCKET_TIMEOUT = 1

# MAP FILES PATH
DIR_MAP = "../map/"
DIR_TILESET = "../map/tileset/"
